GAME_SRCS = dlls/agrunt.cpp \
	dlls/airtank.cpp \
	dlls/aflock.cpp \
	dlls/animating.cpp \
	dlls/animation.cpp \
	dlls/apache.cpp \
	dlls/barnacle.cpp \
	dlls/barney.cpp \
	dlls/bigmomma.cpp \
	dlls/bloater.cpp \
	dlls/bmodels.cpp \
	dlls/bullsquid.cpp \
	dlls/buttons.cpp \
	dlls/cbase.cpp \
	dlls/client.cpp \
	dlls/combat.cpp \
	dlls/controller.cpp \
	dlls/crossbow.cpp \
	dlls/crowbar.cpp \
	dlls/defaultai.cpp \
	dlls/doors.cpp \
	dlls/effects.cpp \
	dlls/egon.cpp \
	dlls/explode.cpp \
	dlls/flyingmonster.cpp \
	dlls/func_break.cpp \
	dlls/func_tank.cpp \
	dlls/game.cpp \
	dlls/gamerules.cpp \
	dlls/gargantua.cpp \
	dlls/gauss.cpp \
	dlls/genericmonster.cpp \
	dlls/ggrenade.cpp \
	dlls/globals.cpp \
	dlls/glock.cpp \
	dlls/gman.cpp \
	dlls/h_ai.cpp \
	dlls/h_battery.cpp \
	dlls/h_cine.cpp \
	dlls/h_cycler.cpp \
	dlls/h_export.cpp \
	dlls/handgrenade.cpp \
	dlls/hassassin.cpp \
	dlls/headcrab.cpp \
	dlls/healthkit.cpp \
	dlls/hgrunt.cpp \
	dlls/hornet.cpp \
	dlls/hornetgun.cpp \
	dlls/houndeye.cpp \
	dlls/ichthyosaur.cpp \
	dlls/islave.cpp \
	dlls/items.cpp \
	dlls/leech.cpp \
	dlls/lights.cpp \
	dlls/maprules.cpp \
	dlls/monstermaker.cpp \
	dlls/monsters.cpp \
	dlls/monsterstate.cpp \
	dlls/mortar.cpp \
	dlls/mp5.cpp \
	dlls/multiplay_gamerules.cpp \
	dlls/nihilanth.cpp \
	dlls/nodes.cpp \
	dlls/observer.cpp \
	dlls/osprey.cpp \
	dlls/pathcorner.cpp \
	dlls/plane.cpp \
	dlls/plats.cpp \
	dlls/player.cpp \
	dlls/playermonster.cpp \
	dlls/python.cpp \
	dlls/rat.cpp \
	dlls/roach.cpp \
	dlls/rpg.cpp \
	dlls/satchel.cpp \
	dlls/schedule.cpp \
	dlls/scientist.cpp \
	dlls/scripted.cpp \
	dlls/shotgun.cpp \
	dlls/singleplay_gamerules.cpp \
	dlls/skill.cpp \
	dlls/sound.cpp \
	dlls/soundent.cpp \
	dlls/spectator.cpp \
	dlls/squadmonster.cpp \
	dlls/squeakgrenade.cpp \
	dlls/subs.cpp \
	dlls/talkmonster.cpp \
	dlls/teamplay_gamerules.cpp \
	dlls/tempmonster.cpp \
	dlls/tentacle.cpp \
	dlls/triggers.cpp \
	dlls/tripmine.cpp \
	dlls/turret.cpp \
	dlls/util.cpp \
	dlls/vehicle.cpp \
	dlls/weapons.cpp \
	dlls/world.cpp \
	dlls/xen.cpp \
	dlls/zombie.cpp \
	dlls/pm_debug.cpp \
	dlls/pm_math.cpp \
	dlls/pm_shared.cpp \
	dlls/link_helper.cpp 